-- KPI Formulas SQL Insert Script
-- Generated for Solution Integration Profesional HRIS
-- Date: 2026-09-09 01:31:22

-- Clear existing KPI data
DELETE FROM employee_kpis;
DELETE FROM kpi_templates;
DELETE FROM kpi_formulas;

-- Insert KPI Formulas
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Revenue Growth', '(Pendapatan Tahun Ini - Pendapatan Tahun Lalu) / Pendapatan Tahun Lalu x 100%', 'Pertumbuhan pendapatan tahunan', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Net Profit Margin', '(Laba Bersih / Total Pendapatan) x 100%', 'Margin keuntungan bersih', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Opex Ratio', '(Total Biaya Operasional / Total Pendapatan) x 100%', 'Rasio biaya operasional', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Pipeline Contribution', 'Pipeline Aktif / Total Revenue x 100%', 'Kontribusi pipeline terhadap revenue', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Staffing Completion', 'Posisi Terisi / Total Posisi x 100%', 'Kelengkapan formasi tim', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Financial Report Accuracy', '1 - (Jumlah Error / Total Transaksi) x 100%', 'Akurasi laporan keuangan', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('DSO', 'Total Piutang / (Penjualan Kredit / 30)', 'Days Sales Outstanding', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Cash Flow Efficiency', 'Kas Operasional / Kebutuhan Operasional x 100%', 'Efisiensi cash flow', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Social Media Growth', '(Followers Bulan Ini - Followers Bulan Lalu) / Followers Bulan Lalu x 100%', 'Pertumbuhan followers media sosial', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Win Rate Support', 'Proyek Menang Didukung / Total Proyek Didukung x 100%', 'Rasio dukungan kemenangan proyek', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Design Accuracy', '1 - (Design Errors / Total Designs) x 100%', 'Akurasi desain BoQ', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('TKDN Process Time', 'Durasi Proses (hari)', 'Waktu proses TKDN', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Building Maintenance', 'Maintenance Selesai / Total Maintenance x 100%', 'Penyelesaian perawatan gedung', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Procurement Accuracy', 'Pengadaan Sesuai Harga / Total Pengadaan x 100%', 'Akurasi pengadaan supplier', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Installation SLA', 'Proyek Tepat Waktu / Total Proyek x 100%', 'SLA penyelesaian instalasi', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Recall Rate', 'Pekerjaan Diulang / Total Pekerjaan x 100%', 'Tingkat pekerjaan yang harus diulang', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Response Time', 'Waktu Respon Rata-rata (jam)', 'Kecepatan respon troubleshooting', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Inventory Accuracy', 'Barang Sesuai / Total Barang x 100%', 'Akurasi stock opname', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Delivery SLA', 'Pengiriman Tepat Waktu / Total Pengiriman x 100%', 'SLA pengiriman barang', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Revenue Achievement', 'Total PO Masuk / Target Sales x 100%', 'Pencapaian target pendapatan', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Lead Conversion Rate', 'Leads Terkonversi / Total Leads x 100%', 'Tingkat konversi prospek', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES ('Repeat Order Rate', 'Repeat Order / Total Order x 100%', 'Tingkat pemesanan ulang', 'general');
INSERT INTO kpi_formulas (formula_name, formula, description, category) VALUES (NULL, NULL, NULL, 'general');

-- Insert KPI Templates
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Revenue Growth', 'Executive', 'Director', 'Revenue Growth', 'Sesuai RUPS (Toleransi 80% dari target ideal)', 40.0, '{"1": "<50%", "2": "50-69%", "3": "70-85%", "4": "86-100%", "5": ">100%"}', 'Fase transisi - fokus pembentukan kebiasaan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Profit Margin', 'Executive', 'Director', 'Net Profit Margin', 'Tercapai target margin minimal', 20.0, '{"1": "<50%", "2": "50-69%", "3": "70-85%", "4": "86-100%", "5": ">100%"}', 'Target margin sesuai kesepakatan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Opex Efficiency', 'Executive', 'Director', 'Opex Ratio', 'Batas Opex dengan toleransi deviasi 5%', 20.0, '{"1": ">120%", "2": "110-120%", "3": "100-110%", "4": "95-100%", "5": "<95%"}', 'Efisiensi biaya operasional');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Pipeline Development', 'Executive', 'Director', 'Pipeline Contribution', 'Minimal 5 pipeline dengan kontribusi minimal 10% dari total revenue', 10.0, '{"1": "0-1 pipeline", "2": "2-3 pipeline", "3": "4-5 pipeline", "4": "6-8 pipeline", "5": ">8 pipeline"}', 'Pipeline aktif dari network pribadi');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Team Formation', 'Executive', 'Director', 'Staffing Completion', 'Struktur terisi & beroperasi 90%', 10.0, '{"1": "<50%", "2": "50-69%", "3": "70-85%", "4": "86-95%", "5": ">95%"}', 'Penyelesaian formasi struktur');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Financial Accuracy', 'Finance', 'Head Finance', 'Financial Report Accuracy', 'Akurasi 95% (Toleransi minor/bukan material)', 30.0, '{"1": "<80%", "2": "80-85%", "3": "85-90%", "4": "90-95%", "5": ">95%"}', 'Akurasi laporan keuangan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Reporting SLA', 'Finance', 'Head Finance', 'Reporting Timeliness', 'Setiap tanggal 15 bulan berikutnya', 25.0, '{"1": ">20 hari", "2": "18-20 hari", "3": "16-17 hari", "4": "15 hari", "5": "<15 hari"}', 'Ketepatan waktu pelaporan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('DSO Management', 'Finance', 'Head Finance', 'DSO', 'Sesuai Term of Payment + Toleransi 7 Hari', 25.0, '{"1": ">45 hari", "2": "38-45 hari", "3": "31-37 hari", "4": "24-30 hari", "5": "<24 hari"}', 'Days Sales Outstanding');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Cash Flow Efficiency', 'Finance', 'Head Finance', 'Cash Flow Efficiency', 'Operasional penting (gaji/sewa/vendor utama) terbayar', 20.0, '{"1": "Keterlambatan >7 hari", "2": "Keterlambatan 5-7 hari", "3": "Keterlambatan 3-4 hari", "4": "Keterlambatan 1-2 hari", "5": "Tepat waktu"}', 'Efisiensi cash flow management');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Social Media Growth', 'Marketing', 'Digital Marketing', 'Social Media Growth', '30 followers baru per bulan', 15.0, '{"1": "<10/bulan", "2": "10-19/bulan", "3": "20-29/bulan", "4": "30-40/bulan", "5": ">40/bulan"}', 'Pertumbuhan followers media sosial');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Video Production', 'Marketing', 'Digital Marketing', 'Video Content Creation', 'Minimal 5 video per bulan', 15.0, '{"1": "<2 video", "2": "2-3 video", "3": "4-5 video", "4": "6-8 video", "5": ">8 video"}', 'Video aktivitas dan produk');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Digital Lead Generation', 'Marketing', 'Digital Marketing', 'Lead Generation', 'Aset digital rapi & ada aliran leads (prospek) awal', 15.0, '{"1": "Tidak ada leads", "2": "1-5 leads/bulan", "3": "6-10 leads/bulan", "4": "11-20 leads/bulan", "5": ">20 leads/bulan"}', 'Lead generation & pemasaran digital');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Win Rate Support', 'Marketing', 'Presales', 'Win Rate Support', 'Minimal 25% - 30% Win Rate Dukungan', 20.0, '{"1": "<15%", "2": "15-19%", "3": "20-24%", "4": "25-30%", "5": ">30%"}', 'Rasio dukungan kemenangan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Design Accuracy', 'Marketing', 'Presales', 'Design Accuracy', '0% error tolerance (zero design errors)', 20.0, '{"1": ">5% error", "2": "3-5% error", "3": "1-2% error", "4": "0.1-1% error", "5": "0% error"}', 'Akurasi desain BoQ');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Design SLA', 'Marketing', 'Presales', 'Design & Proposal SLA', 'Penyelesaian 90% on-time (maks. perpanjangan 1 hari)', 15.0, '{"1": "<70% on-time", "2": "70-79%", "3": "80-89%", "4": "90-95%", "5": ">95%"}', 'SLA penyusunan desain & proposal');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('TKDN Process', 'Operations', 'General Affairs', 'TKDN Process Time', 'Maksimal 150 hari', 40.0, '{"1": ">200 hari", "2": "176-200 hari", "3": "151-175 hari", "4": "126-150 hari", "5": "<125 hari"}', 'TKDN proses');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Building Maintenance', 'Operations', 'General Affairs', 'Building Maintenance', 'Direspon & di-follow up dalam hari yang sama', 25.0, '{"1": ">3 hari", "2": "2-3 hari", "3": "1-2 hari", "4": "Hari yang sama", "5": "<2 jam"}', 'Perawatan gedung');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Procurement Accuracy', 'Operations', 'General Affairs', 'Procurement Accuracy', 'Minimal 3 vendor', 15.0, '{"1": "<1 vendor", "2": "1-2 vendor", "3": "3-4 vendor", "4": "5-6 vendor", "5": ">6 vendor"}', 'Pengadaan & manajemen supplier lokal');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('HR Operations', 'Operations', 'General Affairs', 'HR & Operational Management', 'Progres perapihan arsip terlihat tiap bulan', 10.0, '{"1": "Tidak ada progres", "2": "Sedikit progres", "3": "Progres sedang", "4": "Progres baik", "5": "Progres sangat baik"}', 'Manajemen SDM & operasional');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Maintenance Response', 'Operations', 'General Affairs', 'Maintenance Response Time', '<12 jam', 10.0, '{"1": ">24 jam", "2": "18-24 jam", "3": "12-18 jam", "4": "6-12 jam", "5": "<6 jam"}', 'Respon perbaikan kerusakan gedung');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Installation SLA', 'Operations', 'Technical', 'Installation SLA', 'Tercapai 90% (ada toleransi penyesuaian jadwal)', 35.0, '{"1": "<70%", "2": "70-79%", "3": "80-89%", "4": "90-95%", "5": ">95%"}', 'SLA penyelesaian instalasi/proyek');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Recall Rate', 'Operations', 'Technical', 'Recall Rate', 'Maksimal 5% Recall Rate dari total proyek', 30.0, '{"1": ">10%", "2": "7-10%", "3": "5-7%", "4": "3-5%", "5": "<3%"}', 'Tingkat recall pekerjaan diulang');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Response Time', 'Operations', 'Technical', 'Troubleshooting Response Time', 'Maks. 1 Jam (Response) selama jam kerja dan 3 jam di luar jam kerja', 25.0, '{"1": ">4 jam", "2": "3-4 jam", "3": "2-3 jam", "4": "1-2 jam", "5": "<1 jam"}', 'Kecepatan respon troubleshooting');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Field Reporting', 'Operations', 'Technical', 'Field Reporting Compliance', 'Konsistensi pelaporan 90%', 10.0, '{"1": "<60%", "2": "60-69%", "3": "70-84%", "4": "85-95%", "5": ">95%"}', 'Kerapihan kerja & pelaporan lapangan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Inventory Accuracy', 'Operations', 'Warehouse', 'Inventory Accuracy', 'Akurasi 95% (Toleransi masa perapihan 5%)', 50.0, '{"1": "<80%", "2": "80-85%", "3": "86-90%", "4": "91-95%", "5": ">95%"}', 'Akurasi inventory stock opname');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Delivery SLA', 'Operations', 'Warehouse', 'Delivery SLA', 'Tercapai 90% tepat waktu (minim keterlambatan)', 30.0, '{"1": "<70%", "2": "70-79%", "3": "80-89%", "4": "90-95%", "5": ">95%"}', 'SLA pemrosesan & pengiriman barang');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Warehouse Organization', 'Operations', 'Warehouse', '5R Implementation', 'Terlihat perbaikan tata letak & pelabelan dasar', 10.0, '{"1": "Tidak ada perbaikan", "2": "Mulai diperbaiki", "3": "Cukup rapi", "4": "Rapi dan terlabel", "5": "Sangat rapi dan terstandarisasi"}', 'Penataan gudang 5R dasar');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Fleet Maintenance', 'Operations', 'Warehouse', 'Fleet & Document Management', 'Minim keluhan & surat jalan terarsipkan lengkap', 10.0, '{"1": "Banyak keluhan", "2": "Beberapa keluhan", "3": "Sedikit keluhan", "4": "Minim keluhan", "5": "Tidak ada keluhan"}', 'Pemeliharaan armada & dokumen jalan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Revenue Achievement', 'Sales', 'Sales Executive', 'Revenue Achievement', 'Minimal 75% dari Target Kuartalan tercapai', 35.0, '{"1": "<50%", "2": "50-64%", "3": "65-74%", "4": "75-85%", "5": ">85%"}', 'Pencapaian target pendapatan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Pipeline Development', 'Sales', 'Sales Executive', 'Pipeline Growth', 'Minimal 15 pipeline baru per minggu', 25.0, '{"1": "<5/minggu", "2": "5-9/minggu", "3": "10-14/minggu", "4": "15-20/minggu", "5": ">20/minggu"}', 'Kunjungan pipeline baru');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Lead Conversion', 'Sales', 'Sales Executive', 'Lead Conversion Rate', 'Minimal 20% leads terkonversi', 15.0, '{"1": "<10%", "2": "10-14%", "3": "15-19%", "4": "20-25%", "5": ">25%"}', 'Conversion rate pipeline');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Customer Retention', 'Sales', 'Sales Executive', 'Repeat Order Rate', 'Minimal 1-2 Repeat Order / Kuartal', 15.0, '{"1": "0 repeat", "2": "1 repeat/2 kuartal", "3": "1 repeat/kuartal", "4": "2 repeat/kuartal", "5": ">2 repeat/kuartal"}', 'Retensi & repeat order pelanggan');
INSERT INTO kpi_templates (template_name, department, position, kpi_name, target_standard, weight_percentage, scoring_scale, transition_notes) VALUES ('Product Knowledge', 'Sales', 'Sales Executive', 'Product Knowledge Assessment', 'Lulus evaluasi internal dasar', 10.0, '{"1": "Tidak lulus", "2": "Perlu perbaikan", "3": "Memenuhi dasar", "4": "Baik", "5": "Sangat baik"}', 'Pengetahuan produk & adaptasi solusi');

-- Insert Employee KPI Assignments
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 1, id, '2026-Q1', 'Progres perapihan arsip terlihat tiap bulan' FROM kpi_templates WHERE template_name = 'TKDN Process';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 1, id, '2026-Q1', '<12 jam' FROM kpi_templates WHERE template_name = 'Building Maintenance';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 2, id, '2026-Q1', 'Progres perapihan arsip terlihat tiap bulan' FROM kpi_templates WHERE template_name = 'TKDN Process';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 3, id, '2026-Q1', 'Tercapai 90%' FROM kpi_templates WHERE template_name = 'Installation SLA';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 3, id, '2026-Q1', 'Maksimal 5% Recall Rate' FROM kpi_templates WHERE template_name = 'Recall Rate';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 3, id, '2026-Q1', 'Maks. 1 Jam (Response)' FROM kpi_templates WHERE template_name = 'Response Time';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 3, id, '2026-Q1', 'Konsistensi pelaporan 90%' FROM kpi_templates WHERE template_name = 'Field Reporting';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 4, id, '2026-Q1', 'Tercapai 90%' FROM kpi_templates WHERE template_name = 'Installation SLA';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 4, id, '2026-Q1', 'Maksimal 5% Recall Rate' FROM kpi_templates WHERE template_name = 'Recall Rate';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 4, id, '2026-Q1', 'Maks. 1 Jam (Response)' FROM kpi_templates WHERE template_name = 'Response Time';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 5, id, '2026-Q1', 'Tercapai 90%' FROM kpi_templates WHERE template_name = 'Installation SLA';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 5, id, '2026-Q1', 'Maksimal 5% Recall Rate' FROM kpi_templates WHERE template_name = 'Recall Rate';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 5, id, '2026-Q1', 'Maks. 1 Jam (Response)' FROM kpi_templates WHERE template_name = 'Response Time';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 6, id, '2026-Q1', 'Minimal 15 pipeline baru per minggu' FROM kpi_templates WHERE template_name = 'Win Rate Support';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 6, id, '2026-Q1', 'Minimal 20% leads terkonversi' FROM kpi_templates WHERE template_name = 'Design Accuracy';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 6, id, '2026-Q1', 'Minimal 1-2 Repeat Order / Kuartal' FROM kpi_templates WHERE template_name = 'Social Media Growth';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 6, id, '2026-Q1', 'Lulus evaluasi internal dasar' FROM kpi_templates WHERE template_name = 'Video Production';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 6, id, '2026-Q1', 'Minimal 75% dari Target Kuartalan' FROM kpi_templates WHERE template_name = 'Product Knowledge';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', '30 followers baru per bulan' FROM kpi_templates WHERE template_name = 'Inventory Accuracy';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', 'Minimal 5 video per bulan' FROM kpi_templates WHERE template_name = 'Delivery SLA';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', 'Minimal 25% - 30% Win Rate Dukungan' FROM kpi_templates WHERE template_name = 'Design SLA';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', '0% error tolerance' FROM kpi_templates WHERE template_name = 'Digital Lead Generation';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', 'Penyelesaian 90% on-time' FROM kpi_templates WHERE template_name = 'Warehouse Organization';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 7, id, '2026-Q1', 'Aset digital rapi & ada aliran leads' FROM kpi_templates WHERE template_name = 'Fleet Maintenance';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 8, id, '2026-Q1', 'Setiap tanggal 15 bulan berikutnya' FROM kpi_templates WHERE template_name = 'Revenue Achievement';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 8, id, '2026-Q1', 'Sesuai Term of Payment + Toleransi 7 Hari' FROM kpi_templates WHERE template_name = 'Pipeline Development';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 8, id, '2026-Q1', 'Akurasi 95%' FROM kpi_templates WHERE template_name = 'Cash Flow Efficiency';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 8, id, '2026-Q1', 'Operasional penting terbayar' FROM kpi_templates WHERE template_name = 'Lead Conversion';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 9, id, '2026-Q1', 'Setiap tanggal 15 bulan berikutnya' FROM kpi_templates WHERE template_name = 'Revenue Achievement';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 9, id, '2026-Q1', 'Sesuai Term of Payment + Toleransi 7 Hari' FROM kpi_templates WHERE template_name = 'Pipeline Development';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 9, id, '2026-Q1', 'Akurasi 95%' FROM kpi_templates WHERE template_name = 'Cash Flow Efficiency';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 10, id, '2026-Q1', 'Maksimal 150 hari' FROM kpi_templates WHERE template_name = 'Procurement Accuracy';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 10, id, '2026-Q1', 'Direspon & di-follow up dalam hari yang sama' FROM kpi_templates WHERE template_name = 'HR Operations';
INSERT INTO employee_kpis (employee_id, template_id, period, target_value) SELECT 10, id, '2026-Q1', 'Minimal 3 vendor' FROM kpi_templates WHERE template_name = 'Maintenance Response';
